echo "updates account data at specific id, NOTE: replace 'id' in 'http://localhost:3000/accounts/id' with the id generated by the previous POST command"
curl -H "Content-Type: application/json" -X PUT -d '{"balance": "1500"}' "http://localhost:3000/accounts/$1"
echo; echo